# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-17 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('text2', models.TextField()),
                ('text3', models.TextField()),
            ],
        ),
    ]
