# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-17 06:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='text2',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='text',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='text3',
        ),
    ]
