# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-19 14:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20170117_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 1, 19, 14, 2, 57, 158151, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweet',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 1, 19, 14, 3, 47, 379111, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.CharField(max_length=140),
        ),
    ]
