# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-22 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_tweet_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='content',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='user',
        ),
    ]
