# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-22 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_auto_20170122_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='content',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
