# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-23 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0007_auto_20170122_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='content',
        ),
    ]
