# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-23 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0008_remove_tweet_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='content',
            field=models.CharField(default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
    ]
